const CHUNK_SIZE = 1024;
const HEADER_CHUNK_SIZE = 64;
const DATA_CHUNK_SIZE = CHUNK_SIZE - 64;

export const TCP_CONFIG = {
  HOST: '127.0.0.1',
  PORT: 12345,
  MAX_RECONNECT_ATTEMPTS: 10,
  RECONNECT_DELAY: 2000,
  CHUNK_SIZE,
  HEADER_CHUNK_SIZE,
  DATA_CHUNK_SIZE,
};
